# Generated by Django 4.2.3 on 2023-07-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='writer',
        ),
    ]
