# Generated by Django 4.2.3 on 2023-07-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HTML/CSS', 'HTML / CSS'), ('Python', 'Python'), ('Django', 'Django'), ('고양이', '고양이')], max_length=50),
        ),
    ]
